// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Form$ReactTemplate = require("./Form/Form.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Form$ReactTemplate.make(/* array */[])), "form");

/*  Not a pure module */
